config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  belongs_to :unit

  default_scope { order(index: :asc) }

  def to_s
    adjusted_quantity = quantity == '0/1' ? '' : quantity
    "#{adjusted_quantity} #{unit} #{ingredient}".strip
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  def to_s
    name
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :text, presence: true

  has_many :components
  has_many :ingredients, through: :components

  default_scope { order(rating: :desc, name: :asc) }
end

app/models/unit.rb
class Unit < ApplicationRecord
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :rating, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def rating_stars(recipe)
    ('* ' * recipe.rating).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sozzler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div> <!-- /.container -->
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="ui fluid search">
  <div class="ui icon input">
    <input class="prompt" type="text" placeholder="Search..." autofocus>
    <i class="search icon"></i>
  </div>
  <div class="results"></div>
</div>

<div class="ui divider"></div>

<div class="ui divided link items recipes">
  <% @recipes.each do |recipe| %>
    <a class="item" href="<%= url_for(recipe) %>" data-recipe-id="<%= recipe.id %>">
      <div class="content">
        <div class="header"><%= recipe.name %></div>
        <div class="meta">
          <span class="recipe-rating"><div class="ui star rating" data-rating="<%= recipe.rating %>" data-max-rating="5"></div></span>
        </div>
        <div class="description">
          <p><%= recipe.ingredients.map(&:name).join(', ') %></p>
        </div>
      </div>
    </a>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <div>
    <h1><%= @recipe.name %></h1>
    <div class="ui star rating" data-rating="<%= @recipe.rating %>" data-max-rating="5"></div>
  </div>
</div>

<div class="ui divider"></div>

<div>
  <% @recipe.components.each do |component| %>
    <div>
      <%= component %>
    </div>
  <% end %>
</div>

<div>
  <div>
    <div class="recipe-text">
      <%= @recipe.text %>
    </div>
  </div>
</div>